# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 76910a3d4f4f83a2d735b29c9e44480758ecf84a277153e7e52f338cafc89a5a1fb5c03b1e06fe3c0fa86340f31177b65f0888d8ed61af3e534f1243d7d797bb

test:
  secret_key_base: e209dd7198d8199166e37f533a9b1a4dea81234265c9428c7fdf8f6e75e0d49673a83c032a6e760ff856b997f8a47fa69a0b6ac4f111961fdb75207a95faa68e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
